export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS"="WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR"="WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED"="WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_GET_LIST:"WS_FEED_GET_LIST"="WS_FEED_GET_LIST";
export const WS_FEED_CONNECTION_START:"WS_FEED_CONNECTION_START"="WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_END:"WS_FEED_CONNECTION_END"="WS_FEED_CONNECTION_END";
export const constWebsocketActionsFeed={
    onOpen: WS_FEED_CONNECTION_SUCCESS,
    onClose:  WS_FEED_CONNECTION_CLOSED,
    onError:  WS_FEED_CONNECTION_ERROR,
    onNewList: WS_FEED_GET_LIST, 
    wsInit:  WS_FEED_CONNECTION_START,
    wsEnd: WS_FEED_CONNECTION_END,
}