export const DOWNLOAD_INGREDIENTS_REQUEST: 'DOWNLOAD_INGREDIENTS_REQUEST' = 'DOWNLOAD_INGREDIENTS_REQUEST';
export const DOWNLOAD_INGREDIENTS_FAILED: 'DOWNLOAD_INGREDIENTS_FAILED' = 'DOWNLOAD_INGREDIENTS_FAILED';
export const DOWNLOAD_INGREDIENTS_SUCCES: 'DOWNLOAD_INGREDIENTS_SUCCES' = 'DOWNLOAD_INGREDIENTS_SUCCES';
export const INCREASE_INGREDIENT_AMOUNT: 'INCREASE_INGREDIENT_AMOUNT' = 'INCREASE_INGREDIENT_AMOUNT';
export const DECREASE_INGREDIENT_AMOUNT: 'DECREASE_INGREDIENT_AMOUNT' = 'DECREASE_INGREDIENT_AMOUNT';
export const CHANGE_BUNS: 'CHANGE_BUNS' = 'CHANGE_BUNS';
export const REFRESH_TABS: 'REFRESH_TABS' = 'REFRESH_TABS';
export const CLEAN_SELECTED_INGREDIENTS: 'CLEAN_SELECTED_INGREDIENTS' = 'CLEAN_SELECTED_INGREDIENTS';