export const ADD_INGREDIENT_TO_CONSTRUCTOR:'ADD_INGREDIENT_TO_CONSTRUCTOR' = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const DELETE_INGREDIENT_FROM_CONSTRUCTOR:'DELETE_INGREDIENT_FROM_CONSTRUCTOR' = 'DELETE_INGREDIENT_FROM_CONSTRUCTOR';
export const CHANGE_ORDER_BUN:'CHANGE_ORDER_BUN' = 'CHANGE_ORDER_BUN';
export const INIT_CONSTRUCTOR_LIBRARY:"INIT_CONSTRUCTOR_LIBRARY" = "INIT_CONSTRUCTOR_LIBRARY";
export const MOVE_INGREDIENT:"MOVE_INGREDIENT" = "MOVE_INGREDIENT";
export const REFRESH_PRICE:'REFRESH_PRICE' = 'REFRESH_PRICE';
export const CLEAN_CONSTRUCTOR:'CLEAN_CONSTRUCTOR' = 'CLEAN_CONSTRUCTOR';
//export type foodTypesBunSauceMain='bun'|'sauce'|'main'; //возможно на сервере добавят еще какой тип еды кроме этих 3.