export const WS_PROFILE_ORDERS_CONNECTION_SUCCESS: "WS_PROFILE_ORDERS_CONNECTION_SUCCESS"="WS_PROFILE_ORDERS_CONNECTION_SUCCESS";
export const WS_PROFILE_ORDERS_CONNECTION_ERROR: "WS_PROFILE_ORDERS_CONNECTION_ERROR"="WS_PROFILE_ORDERS_CONNECTION_ERROR";
export const WS_PROFILE_ORDERS_CONNECTION_CLOSED: "WS_PROFILE_ORDERS_CONNECTION_CLOSED"="WS_PROFILE_ORDERS_CONNECTION_CLOSED";
export const WS_PROFILE_ORDERS_GET_LIST:"WS_PROFILE_ORDERS_GET_LIST"="WS_PROFILE_ORDERS_GET_LIST";
export const WS_PROFILE_ORDERS_CONNECTION_START: "WS_PROFILE_ORDERS_CONNECTION_START"="WS_PROFILE_ORDERS_CONNECTION_START";
export const WS_PROFILE_ORDERS_CONNECTION_END: "WS_PROFILE_ORDERS_CONNECTION_END"="WS_PROFILE_ORDERS_CONNECTION_END";
export const constWebsocketActionsProfileOrders={
    onOpen:  WS_PROFILE_ORDERS_CONNECTION_SUCCESS,
    onClose: WS_PROFILE_ORDERS_CONNECTION_CLOSED,
    onError: WS_PROFILE_ORDERS_CONNECTION_ERROR,
    onNewList: WS_PROFILE_ORDERS_GET_LIST,
    wsInit: WS_PROFILE_ORDERS_CONNECTION_START,
    wsEnd: WS_PROFILE_ORDERS_CONNECTION_END,
}