export const LOAD_ORDER_REQUEST:'LOAD_ORDER_REQUEST' = 'LOAD_ORDER_REQUEST';
export const LOAD_ORDER_REQUEST_SUCCES:'LOAD_ORDER_REQUEST_SUCCES' = 'LOAD_ORDER_REQUEST_SUCCES';
export const LOAD_ORDER_REQUEST_FAILED:'LOAD_ORDER_REQUEST_FAILED' = 'LOAD_ORDER_REQUEST_FAILED';
export const CLEAR_ORDER:'CLEAR_ORDER' = 'CLEAR_ORDER';
export const SUSPEND_ORDER:'SUSPEND_ORDER' = 'SUSPEND_ORDER';